# Generated by Django 6.1 on 2026-09-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billetterie', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='agent_gare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billets_vendus', to='comptes.agentgare'),
        ),
        migrations.AddField(
            model_name='billet',
            name='passager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='comptes.passager'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='billet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='billetterie.billet'),
        ),
        migrations.AddField(
            model_name='billet',
            name='siege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billets', to='billetterie.siege'),
        ),
        migrations.AddField(
            model_name='billet',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billets', to='billetterie.tarif'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='gare_arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages_a_larrivee', to='billetterie.gare'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='gare_depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages_au_depart', to='billetterie.gare'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='billetterie.train'),
        ),
        migrations.AddField(
            model_name='billet',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='billetterie.voyage'),
        ),
        migrations.AddField(
            model_name='wagon',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagons', to='billetterie.train'),
        ),
        migrations.AddField(
            model_name='siege',
            name='wagon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sieges', to='billetterie.wagon'),
        ),
        migrations.AlterUniqueTogether(
            name='wagon',
            unique_together={('train', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='siege',
            unique_together={('wagon', 'numero')},
        ),
    ]
