# Generated by Django 6.1 on 2026-09-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0002_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='billet',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['EN_ATTENTE', 'CONFIRME'])), fields=('voyage', 'siege'), name='unique_siege_par_voyage_actif'),
        ),
    ]
