# Generated by Django 6.1 on 2026-09-05 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0003_billet_unique_siege_par_voyage_actif'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billet',
            name='unique_siege_par_voyage_actif',
        ),
    ]
