# Generated by Django 6.1 on 2026-09-17 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0004_remove_billet_unique_siege_par_voyage_actif'),
        ('comptes', '0002_passager_solde_orange_money_passager_solde_wave'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='gare_debarquement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billets_debarquement', to='billetterie.gare'),
        ),
        migrations.AddField(
            model_name='billet',
            name='gare_embarquement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billets_embarquement', to='billetterie.gare'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='billet',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['EN_ATTENTE', 'CONFIRME'])), fields=('voyage', 'siege'), name='unique_siege_par_voyage_actif'),
        ),
        migrations.AddConstraint(
            model_name='voyage',
            constraint=models.UniqueConstraint(fields=('gare_depart', 'gare_arrivee', 'date_heure_depart'), name='unique_voyage_par_creneau'),
        ),
    ]
