# Generated by Django 6.1 on 2026-09-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0005_billet_gare_debarquement_billet_gare_embarquement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='supprime',
            field=models.BooleanField(default=False),
        ),
    ]
