# Generated by Django 6.1 on 2026-09-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passager',
            name='solde_orange_money',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name='passager',
            name='solde_wave',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
    ]