# Generated by Django 6.1 on 2026-09-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billetterie', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.CharField(choices=[('VALIDE', 'Valide'), ('BILLET_EXPIRE', 'Billet expire'), ('MAUVAISE_CLASSE', 'Mauvaise classe'), ('FRAUDE_QR', 'Fraude QR')], max_length=20)),
                ('date_controle', models.DateTimeField(auto_now_add=True)),
                ('billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='billetterie.billet')),
                ('controleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='comptes.controleur')),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles', to='billetterie.gare')),
            ],
        ),
    ]
