# Generated by Django 6.1 on 2026-09-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='resultat',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('BILLET_EXPIRE', 'Billet expire'), ('MAUVAISE_CLASSE', 'Mauvaise classe'), ('FRAUDE_QR', 'Fraude QR'), ('DEJA_VALIDE', 'Deja valide (reutilisation)')], max_length=20),
        ),
    ]