# Generated by Django 6.1 on 2026-09-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billetterie', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WIFI', 'Wi-Fi'), ('PRISE_ELECTRIQUE', 'Prise electrique'), ('CLIMATISATION', 'Climatisation'), ('CONFORT_SIEGE', 'Confort du siege')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('wagon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_premium', to='billetterie.wagon')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Resolue')], default='OUVERTE', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='comptes.passager')),
                ('service_premium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='premium.servicepremium')),
            ],
        ),
    ]
